# Generated by Django 3.2 on 2021-05-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_bla_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product_image', verbose_name='Картинка продукта'),
        ),
    ]
