# Generated by Django 3.2 on 2021-05-09 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='Image_About_Us', verbose_name='Картинка о нас')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='acc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Account', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
    ]
