# Generated by Django 3.2 on 2021-05-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210509_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name': 'Связи и контакты',
                'verbose_name_plural': 'Связи и контакты',
            },
        ),
    ]
